version: '3'

services:

  elastic:
    build: ./elastic
    container_name: g-elastic
    hostname: g-elastic
    image: g-elastic
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m -Des.http.cname_in_publish_address=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      gargoyle:
        ipv4_address: 172.23.0.5
    ports:
      - "59200:9200"
    extra_hosts:
      - "g-db:172.23.0.2"
      - "g-engine:172.23.0.4"
      - "g-api:172.23.0.3"
      - "g-kibana:172.23.0.6"
    volumes:
      - g-elastic_vol:/opt/es-data
    restart: always


  db:
    build: 
      context: ./db
      args:
        - dbpass=${DB_PW}
    container_name: g-db
    image: g-db
    hostname: g-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
    networks:
      gargoyle:
        ipv4_address: 172.23.0.2
    extra_hosts:
      - "g-api:172.23.0.3"
      - "g-engine:172.23.0.4"
      - "g-elastic:172.23.0.5"
      - "g-kibana:172.23.0.6"
    restart: always


  api:
    build: ./api
    container_name: g-api
    hostname: g-api
    image: g-api
    environment:
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - API_USER=${API_USER}
      - API_PW=${API_PW}
    networks:
      gargoyle:
        ipv4_address: 172.23.0.3
    ports:
      - "55000:5000"
    extra_hosts:
      - "g-db:172.23.0.2"
      - "g-engine:172.23.0.4"
      - "g-elastic:172.23.0.5"
      - "g-kibana:172.23.0.6"
    restart: always


  kibana:
    build: ./kibana
    container_name: g-kibana
    hostname: g-kibana
    image: g-kibana
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PW=${ELASTIC_PW}
    networks:
      gargoyle:
        ipv4_address: 172.23.0.6
    ports:
      - "55601:5601"
    extra_hosts:
      - "g-db:172.23.0.2"
      - "g-engine:172.23.0.4"
      - "g-api:172.23.0.3"
      - "g-elastic:172.23.0.5"
    restart: always


  engine:
    build: ./engine
    container_name: g-engine
    hostname: g-engine
    image: g-engine
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PW=${ELASTIC_PW}
      - KIBANA_USER=${KIBANA_USER}
      - KIBANA_PW=${KIBANA_PW}
      - API_USER=${API_USER}
      - API_PW=${API_PW}
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PW=${DB_ROOT_PW}
    networks:
      gargoyle:
        ipv4_address: 172.23.0.4
    extra_hosts:
      - "g-db:172.23.0.2"
      - "g-kibana:172.23.0.6"
      - "g-api:172.23.0.3"
      - "g-elastic:172.23.0.5"
    volumes:
      - g-engine_vol:/var/log/gargoyle
    restart: always


networks:
  gargoyle:
    ipam:
      config:
        - subnet: 172.23.0.0/28

volumes:
  g-elastic_vol:
    external: true
  g-engine_vol:
    external: true
